### ISSUE TITLE
signaling issue for anastasiia-zolochevska/signaling-server (redirect)

### ISSUE THREAD

**Issue by parandham03** [CatalystCode/3dtoolkit#167]
when i click Deploy to Azure button i just see like below.but nothing happen 

![capture](https://user-images.githubusercontent.com/38241337/38542252-031ccf08-3cbf-11e8-81e4-4b281cb8b415.PNG)

please help me solve the issue.

**Comment by bengreenier** [comment]
Hello @parandham03, it looks like there is currently an issue with the [azure deploy](https://deploy.azure.com) site - as it isn't a microsoft service that has an SLA (it's provided as-is as a developer tool) there isn't much we can do. ☹️ 

 ![image](https://user-images.githubusercontent.com/1167891/38564679-a25c7aa8-3cad-11e8-95c2-b003476676ee.png)

I would advise following the instructions [here](https://docs.microsoft.com/en-us/azure/app-service/app-service-continuous-deployment) to deploy using a different method - In my experience, forking the repository and choosing to deploy from Github has worked well. 🚀 

Hope that helps! I'm going to close this issue here, and advise you to please open issues against https://github.com/anastasiia-zolochevska/signaling-server/issues in the future, as that is the project that we'd want to track these sorts of issues on. Thanks! 👍
