### ISSUE TITLE
On peer connection, the video stream does not always start correctly

### ISSUE THREAD

**Issue by anderm** [CatalystCode/3dtoolkit#175]
This is an intermittent issue when a client connect to to the sample server but no video feed is shown. The sample server sees the client as connected but no stream is sent. When a second client connects to the same server, the stream works correctly. 

Repro steps:
Run a multi-peer signaling server [webrtc-signal-http-capacity](https://github.com/bengreenier/webrtc-signal-http-capacity) 
Start any sample server locally or on a remote VM 
Connect multiple clients to the server and eventually one connection will not start the video
Connect another client to the same server and the video stream will work

**Comment by KanishkT123** [comment]
Seems like this is an intermittent problem with the DirectX client, but not one with the Web Client. 

I suspect there is a race condition involved in the DirectX client somewhere. After writing logging software for the client, the video stream issue seems to disappear completely, possibly because the time lag caused by having to create a new file to log to solves the race condition. 

The Web Client, after stress testing, did not have any similar problems on the software encoder. I will test it with the hardware encoder and comment back.

**Comment by KanishkT123** [comment]
This issue also uncovered issue #224 as the signaling client could not properly connect the client to the rendering server. This is a separate issue and the fix would most likely happen in the signaling server repo.

**Comment by KanishkT123** [comment]
After testing the hardware encoder and web client repeatedly, the issue as given in the reproduction steps did not resurface. I think is a bug with the directX client.
