### ISSUE TITLE
Fractal Server + DxHoloClient is giving flat planar render, no depth

### ISSUE THREAD

**Issue by winodesv** [CatalystCode/3dtoolkit#192]
Hi 
I enabled stereo render for Fractal Unity Server, and used DirectxHololensClient to stream to Hololens. I enabled stereo rendering at server. Don't know what was wrong, but I saw only planar render on hololens. Attaching [video link](https://youtu.be/CCXyPAlIDDs).

Please advice what to do to make it render like a hologram.

**Comment by phongcao** [comment]
Can you first try enabling **UNITY_UV_STARTS_AT_TOP** flag in the client? Check it [here](https://github.com/CatalystCode/3dtoolkit/tree/master/Samples/Server/Unity-FractalStream).

**Comment by treisto** [comment]
For me this pair worked fine. There are large variations in frame/latency but first I must upgrade the server (now laptop) and see if performance improves.

**Comment by rishi-rranjan** [comment]
@phongcao @winodesv @treisto I have tried this by setting the UNITY_UV_STARTS_AT_TOP  flag in the client and here are my observations: 

Server + Client used: Unity Fractal Stream server, DirectxHololensClient

1. FPS is very low. It's most of the time 5 FPS. It's not an issue with my network since I am running on 11AC network. Also SpinningCubeServer gives me 60 FPS. My desktop is also pretty powerful. 
![fps](https://user-images.githubusercontent.com/5673695/40272298-e42412fe-5b5f-11e8-8eac-86180f4fc787.PNG)
2. The fractal server rendering shows up in a windows as reported by @winodesv. 
3. **Is there restriction on FPS for stereo mode?** I see that for non stereo mode rate limiter is set to 60 FPS but I am not sure what is set for non stereo mode.  

Server + Client used: 3DStreamingToolkit-DirectX-SpinningCubeServer, DirectxHololensClient

1. FPS is at 57. ![capture](https://user-images.githubusercontent.com/5673695/40272306-044e3686-5b60-11e8-82e1-b5a3e6cb2de7.PNG)

**Comment by winodesv** [comment]
@phongcao Placing hologram involves Hololens assessing physics of real world. As such, (holo)client only has that knowledge. Since our hologram rendering happens at server, do we have a way to communicate this info?

One of the most important features of Hololens is Hologram sharing. So far, Unity3d has support for Hologram sharing. 

Is there something in pipeline for 3Dtoolkit APIs for hologram movement, hologram sharing?

Also, Hololens unity3d client that is under development, do you know if it will be available soon?

**Comment by phongcao** [comment]
@winodesv Regarding hologram placing, right now we haven't supported it. For the sharing, it's one of the feature requests that has been kept track of: #171. HoloLens Unity3d client is having some issues with the Unity FractalStream server but it should work with the SpinningCube/Multithreaded servers.

**Comment by Lenovezhou** [comment]
Can you give me a demo of the HoloLens platform? @winodesv

**Comment by Lenovezhou** [comment]
My app has a black screen on the HoloLens and no log in VisualStudio @winodesv
