### ISSUE TITLE
Create IMediaSource for Audio Data Only (No Video stream)

### ISSUE THREAD

**Issue by znebby** [CatalystCode/3dtoolkit#91]
Hello, we are using this project to create WebRTC calls from a web client to a HoloLens client. In some cases, we wish to send microphone audio only, no video.

Does the UWP webRTC implementation have any methods for creating an IMediaSource or equivalent for audio data alone? It appears that the only function to do this sort of thing takes a MediaVideoTrack as it's input. At the moment we are having the web client stream a blank video stream in order to get the source into a playable format in UWP webRTC.

**Comment by tylergibson** [comment]
@znebby we currently haven't investigated this at all.  Since our toolkit is primarily focused on 3D Visualizations, audio-only isn't something we've tested or plan to invest in deeply.

It should already be supported, see https://github.com/webrtc-uwp/webrtc-windows/blob/5e7289372c5d9f58f0676079e71a4296b6752bcb/org/webrtc/wrapper/Media.h

For specifying audio IMediaStreamTrack and MediaAudioTrack should work.  You may need to extend IMediaSource to handle audio only streams, but if you create the media object only using audio tracks, it should be handled appropriately (in theory, again this isn't something we've tested).

You can also open an issue with webrtc-uwp here: https://github.com/webrtc-uwp/webrtc-windows/issues

Hope that helps!

**Comment by bengreenier** [comment]
i'm going to close this out since we don't have the resources to investigate (and it's a non-goal for us at this point), and we think it's supported.

@znebby i'm happy to separately chat more about your scenario, or if you disagree please reopen! 😸
